version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: system/server/Dockerfile
      args:
        NODE_VERSION: 14
    volumes:
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.resume.rule: Host(`resume.anagraph.org`)
# Uncomment below to earn web access to the project without Traefik
#    ports:
#      - 80:80

volumes:
  caddy_data:
  caddy_config:

# Uncomment below to link with Traefik
networks:
  default:
    external:
      name: proxy