version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: system/Dockerfile
      args:
        NODE_VERSION: 16
        CADDY_VERSION: 2
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.http.routers.resume.rule: Host(`resume.anagraph.org`)
    networks:
      - proxy
      - default

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    external:
      name: reverse_proxy_network